notifications:
  email:
    on_success: never
    on_failure: always

sudo: required

services:
  - docker

language: node_js
node_js:
  - 8

install:
  - npm install

cache:
  directories:
    - "node_modules"

script:
  - npm run cov
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

after_success:
  - npm run build
  - bash Dockerbuild.sh

deploy:
  local-dir: dist
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  fqdn: resource.statnlp.org
  on:
    branch: master

after_deploy:
    - bash Dockerpush.sh
